name: Release Samples

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  release_samples:
    strategy:
      matrix:
        conf: [
          { name: wallet, command: ":sample:wallet:assembleRelease :sample:wallet:appDistributionUploadRelease" },
          { name: dapp, command: ":sample:dapp:assembleRelease :sample:dapp:appDistributionUploadRelease" },
          { name: modal, command: ":sample:modal:assembleRelease :sample:modal:appDistributionUploadRelease" }
        ]
    name: ${{ matrix.conf.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          architecture: x86_64
          cache: 'gradle'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create Google Services Json File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > ./sample/${{ matrix.conf.name}}/google-services.json

      - name: Create Google Services Credentials File
        env:
          GOOGLE_SERVICES_CREDENTIALS_JSON: ${{ secrets.GOOGLE_SERVICES_CREDENTIALS_JSON }}
        run: echo $GOOGLE_SERVICES_CREDENTIALS_JSON | base64 --decode > credentials.json

      - name: Fetch Properties File
        env:
          SECRETS_PROPERTIES: ${{ secrets.SECRETS_PROPERTIES }}
        run: echo $SECRETS_PROPERTIES | base64 --decode > secrets.properties

      - name: Decode Internal Keystore
        env:
          ENCODED_STRING_INTERNAL: ${{ secrets.WC_KOTLIN_INTERNAL_KEYSTORE }}
          SIGNING_KEY_STORE_PATH_INTERNAL: ${{ secrets.WC_KOTLIN_INTERNAL_KEYSTORE_PATH }}
        run: |
          echo $ENCODED_STRING_INTERNAL > keystore-b64.txt
          base64 -d keystore-b64.txt > $SIGNING_KEY_STORE_PATH_INTERNAL

      - name: Decode Upload Keystore
        env:
          ENCODED_STRING_UPLOAD: ${{ secrets.WC_KOTLIN_UPLOAD_KEYSTORE }}
          SIGNING_KEY_STORE_PATH_UPLOAD: ${{ secrets.WC_KOTLIN_UPLOAD_KEYSTORE_PATH }}
        run: |
          echo $ENCODED_STRING_UPLOAD > keystore-b64.txt
          base64 -d keystore-b64.txt > $SIGNING_KEY_STORE_PATH_UPLOAD

      - name: Release sample
        env:
          WC_CLOUD_PROJECT_ID: ${{ secrets.WC_CLOUD_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          NOTIFY_INTEGRATION_TESTS_PROJECT_ID: ${{ secrets.NOTIFY_INTEGRATION_TESTS_PROJECT_ID }}
          NOTIFY_INTEGRATION_TESTS_SECRET: ${{ secrets.NOTIFY_INTEGRATION_TESTS_SECRET }}
        run: ./gradlew ${{ matrix.conf.command }}

      - name: Stop Gradle
        run: ./gradlew --stop
